services:
    # this makes public all the services defined in this file
    _defaults: { public: true }
    
    app.reservation_manager:
        class: AppBundle\Manager\ReservationManager
        arguments:
            - "@=service('doctrine').getManager()"

    app.room_manager:
        class: AppBundle\Manager\RoomManager
        arguments:
            - "@=service('doctrine').getManager()"


    app.user_manager:
            class: AppBundle\Manager\UserManager
            arguments:
                - "@=service('doctrine').getManager()"


    