<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Reservation;
use AppBundle\Entity\Room;
use AppBundle\Entity\User;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * Retourne les réservations d'un mois donné (du mois en cours par défaut)
     *
     * @param \DateTime $date
     *
     * @return Reservation[]
     */
    public function getReservationsOfAYearMonth($date = null)
    {
        if(null === $date){
            $date = new \DateTime();
        }
        
        $first = $date->format('Y-m-01 00:00:00');
        $last = $date->format('Y-m-t 23:59:59');
        
        return $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.date >= :first')
            ->setParameter('first', $first)
            ->andWhere('r.date <= :last')
            ->setParameter('last', $last)
            ->orderBy('r.date', 'ASC')
            ->getQuery()
            ->getResult();
    }
    
    /**
     * Retourne les réservations d'un user
     *
     * @param User $user
     *
     * @return Reservation[]
     */
    public function getReservationsByUser($user)
    {
        return $this->createQueryBuilder('r')
            ->select('r')
            ->leftJoin('r.user', 'u')
            ->where('u.id = :id_user')
            ->setParameter('id_user', $user->getId())
            ->orderBy('r.date', 'DESC')
            ->getQuery()
            ->getResult();
    }
    
    
    /**
     * Retourne les futures réservations d'un user
     *
     * @param User $user
     *
     * @return Reservation[]
     */
    public function getFutureReservationsByUser($user)
    {
        $now = new \DateTime();
        $day = $now->format('Y-m-d 00:00:00');
        
        return $this->createQueryBuilder('r')
            ->select('r')
            ->leftJoin('r.user', 'u')
            ->where('u.id = :id_user')
            ->setParameter('id_user', $user->getId())
            ->andWhere('r.date >= :day')
            ->setParameter('day', $day)
            ->orderBy('r.date', 'DESC')
            ->getQuery()
            ->getResult();
    }
    
    
    
    /**
     * Retourne les futures réservations d'une room
     *
     * @param Room $room
     *
     * @return Reservation[]
     */
    public function getFutureReservationsByRoom($room)
    {
        $now = new \DateTime();
        $day = $now->format('Y-m-d 00:00:00');
        
        return $this->createQueryBuilder('re')
            ->select('re')
            ->leftJoin('re.room', 'ro')
            ->where('ro.id = :id_room')
            ->setParameter('id_room', $room->getId())
            ->andWhere('re.date >= :day')
            ->setParameter('day', $day)
            ->orderBy('re.date', 'ASC')
            ->getQuery()
            ->getResult();
    }
    
    
    
    /**
     * Retourne le nombre de réservations d'une room pour sur un jour donné
     *
     * @param Room $room
     * @param \DateTime $day
     *
     * @return int
     */
    public function getNbReservationsByRoomAndDay($room, $day)
    {
        if(null === $day){
            $day = new \DateTime();
        }
        
        $first = $day->format('Y-m-d 00:00:00');
        $last = $day->format('Y-m-d 23:59:59');
        
        return $this->createQueryBuilder('re')
            ->select('COUNT(re)')
            ->leftJoin('re.room', 'ro')
            ->where('ro.id = :id_room')
            ->setParameter('id_room', $room->getId())
            ->andWhere('re.date >= :first')
            ->setParameter('first', $first)
            ->andWhere('re.date <= :last')
            ->setParameter('last', $last)
            ->getQuery()
            ->getSingleScalarResult();
    }
    
    /**
     * Retourne les réservations pour un jour donné
     *
     * @param \DateTime $day
     *
     * @return Reservation[]
     */
    public function getReservationsByDay($day)
    {
        if(null === $day){
            $day = new \DateTime();
        }
        
        $first = $day->format('Y-m-d 00:00:00');
        $last = $day->format('Y-m-d 23:59:59');
        
        return $this->createQueryBuilder('re')
            ->select('re')
            ->andWhere('re.date >= :first')
            ->setParameter('first', $first)
            ->andWhere('re.date <= :last')
            ->setParameter('last', $last)
            ->getQuery()
            ->getResult();
    }
    
    
    /**
     * Retourne les réservations d'une room pour sur un jour donné
     *
     * @param Int $roomId
     * @param \DateTime $day
     *
     * @return Reservation[]
     */
    public function getReservationsByRoomAndDay($roomId, $day)
    {
        if(null === $day){
            $day = new \DateTime();
        }
        
        $first = $day->format('Y-m-d 00:00:00');
        $last = $day->format('Y-m-d 23:59:59');
        
        return $this->createQueryBuilder('re')
            ->select('re')
            ->leftJoin('re.room', 'ro')
            ->where('ro.id = :id_room')
            ->setParameter('id_room', $roomId)
            ->andWhere('re.date >= :first')
            ->setParameter('first', $first)
            ->andWhere('re.date <= :last')
            ->setParameter('last', $last)
            ->getQuery()
            ->getResult();
    }
    
    /**
     * Retourne les réservations d'une room pour sur un jour donné
     *
     * @param Room $room
     * @param \DateTime $day
     * @param \DateTime $hour
     *
     * @return Reservation[]
     */
    public function getReservationByRoomByDayByHour($room, $day, $hour)
    {
        if(null === $day){
            $day = new \DateTime();
        }
        
        $date = $day->format('Y-m-d');
        $timeBegin = $hour . ':00:00';
        $timeEnd = $hour . ':30:00';
        
        return $this->createQueryBuilder('re')
        ->select('re')
        ->leftJoin('re.room', 'ro')
        ->where('ro.id = :id_room')
        ->setParameter('id_room', $room->getId())
        ->andWhere('re.date = :first')
        ->setParameter('first', $date)
        ->andWhere('re.timeBegin <= :timeBegin')
        ->setParameter('timeBegin', $timeBegin)
        ->andWhere('re.timeEnd <= :timeEnd')
        ->setParameter('timeEnd', $timeEnd)
        ->getQuery()
        ->getResult();
    }
    

}
