<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Reservation;
use AppBundle\Entity\User;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * Retourne les réservations d'un mois donné (du mois en cours par défaut)
     *
     * @param int $mois
     *
     * @return Reservation[]
     */
    public function getReservationsOfAYearMonth($date)
    {
        $first = $date->format('Y-m-01 00:00:00');
        $last = $date->format('Y-m-t 23:59:59');

        
        return $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.dateBegin >= :first')
            ->setParameter('first', $first)
            ->andWhere('r.dateBegin <= :last')
            ->setParameter('last', $last)
            ->orderBy('r.dateBegin', 'ASC')
            ->getQuery()
            ->getResult();
    }
    
    /**
     * Retourne les réservations d'un user (du mois en cours par défaut)
     *
     * @param User $user
     *
     * @return Reservation[]
     */
    public function getReservationsByUser($user)
    {
        
        return $this->createQueryBuilder('r')
        ->select('r')
        ->leftJoin('r.user', 'u')
        ->where('u.id = :id_user')
        ->setParameter('id_user', $user->getId())
        ->orderBy('r.dateBegin', 'DESC')
        ->getQuery()
        ->getResult();
    }


}
