<?php

namespace AppBundle\Repository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * @return Room[]
     */
    public function getRandomRoom(){

        $qb = $this->createQueryBuilder('r')
            ->select('r')
            //->
            ->setMaxResults(1);

        return $qb->getQuery()->getResult();
    }
    
    
}
